- docs/src/09_architecture_decisions.adoc
- docs/src/11_technical_risks.adoc
- docs/src/12_glossary.adoc
Sections 9 and 11 of the documentation are finished and some terms I consider important were added to the glossary.
> chore: Added sections 9 and 11 to the documentation and terms in the glossary

- docs/src/08_concepts.adoc
An build error has been solved, in which not the entire documentation was built.
> hotfix: solve docs build error

- .github/workflows/release.yml
- api/Dockerfile
- api/src/main/java/lab/en2b/quizapi/auth/AuthController.java
- api/src/main/java/lab/en2b/quizapi/auth/AuthService.java
- api/src/main/java/lab/en2b/quizapi/auth/config/SecurityConfig.java
- api/src/main/java/lab/en2b/quizapi/auth/config/UserDetailsImpl.java
- api/src/main/java/lab/en2b/quizapi/auth/dtos/RefreshTokenResponseDto.java
- api/src/main/java/lab/en2b/quizapi/auth/jwt/JwtAuthFilter.java
- api/src/main/java/lab/en2b/quizapi/auth/jwt/JwtUtils.java
- api/src/test/java/lab/en2b/quizapi/QuizApiApplicationTests.java
- docker-compose.yml
- Some code has been cleaned
- Autowired annotations were removed
- New Github actions were created for the SpringBoot API and the PostgreSQL database. 
- Old Github actions were removed.
- New Github secrets were created and they should be added
> feat: deployment Github actions, docker compose for Spring API and code cleaning

- api/pom.xml
- api/src/main/java/lab/en2b/quizapi/auth/AuthService.java
- api/src/main/java/lab/en2b/quizapi/auth/dtos/JwtResponseDto.java
- api/src/main/java/lab/en2b/quizapi/auth/dtos/LoginDto.java
- api/src/main/java/lab/en2b/quizapi/auth/dtos/RefreshTokenDto.java
- api/src/main/java/lab/en2b/quizapi/auth/dtos/RefreshTokenResponseDto.java
- api/src/main/java/lab/en2b/quizapi/auth/dtos/RegisterDto.java
- api/src/main/java/lab/en2b/quizapi/auth/jwt/JwtUtils.java
- api/src/main/java/lab/en2b/quizapi/commons/user/UserService.java
- api/src/main/java/lab/en2b/quizapi/commons/utils/TestUtils.java
- api/src/test/java/lab/en2b/quizapi/auth/AuthControllerTest.java
- api/src/test/java/lab/en2b/quizapi/auth/AuthServiceTest.java
I have added tests for the SpringBoot API testing the following endpoints:
- **/register**
- **/login**
- **/refresh-token**
The tests developed from now on shall follow the same format as the ones provided here.
They shall also be added to a test suit in Github actions as described in #61
> Added tests for the Authentication endpoints

- webapp/src/components/Router.jsx
- webapp/src/index.js
Just a minor PR to replace the JSON-based routing for a declarative one.
> chore: webapp routing rewrite

- api/src/main/java/lab/en2b/quizapi/commons/exceptions/CustomControllerAdvice.java
- api/src/main/java/lab/en2b/quizapi/commons/exceptions/InvalidAuthenticationException.java
- api/src/main/java/lab/en2b/quizapi/commons/user/UserService.java
Invalid credentials now returns a 401 error that actually describes what went wrong instead of returning a 403 with a generic message.
> fix: invalid credentials now returns descriptive error instead of generic one

- api/src/main/java/lab/en2b/quizapi/auth/config/SecurityConfig.java
Fixed mistake with CORS configuration in Spring Boot Security
> fix: cors configuration origins

- webapp/public/locales/en/translation.json
- webapp/public/locales/es/translation.json
- webapp/src/pages/Root.jsx
- webapp/src/pages/Signup.jsx
- webapp/src/tests/Root.test.js
New home funtionality and tests for it.
> feat: Adding the home page and tests for it

- api/src/main/java/lab/en2b/quizapi/auth/AuthController.java
- api/src/main/java/lab/en2b/quizapi/auth/AuthService.java
- api/src/main/java/lab/en2b/quizapi/auth/config/SecurityConfig.java
- api/src/main/java/lab/en2b/quizapi/auth/config/UserDetailsImpl.java
- api/src/main/java/lab/en2b/quizapi/commons/user/UserService.java
- api/src/test/java/lab/en2b/quizapi/auth/AuthControllerTest.java
- api/src/test/java/lab/en2b/quizapi/auth/AuthServiceTest.java
The following was added:
- **/auth/logout** endpoint
- tests for the **/auth/logout** endpoint
The decisions on the implementation will be exposed in #78
> feat: logout endpoint

- webapp/src/components/utils/ProtectedRoute.jsx
- webapp/src/pages/Login.jsx
- webapp/src/pages/Logout.jsx
- webapp/src/pages/Root.jsx
- webapp/src/pages/Signup.jsx
- webapp/src/tests/AuthManager.test.js
- webapp/src/tests/Game.test.js
- webapp/src/tests/Questions.test.js
- webapp/src/tests/Signup.test.js
This PR should fix the webapp tests that do not pass since #145.
> Fix the webapp tests

- webapp/src/tests/AuthManager.test.js
- webapp/src/tests/Login.test.js
- webapp/src/tests/Signup.test.js
This PR fixes some tests not executing due to them being async.
> fix: async tests

- api/src/main/java/lab/en2b/quizapi/questions/question/Question.java
- api/src/main/resources/application.properties
- api/src/test/java/lab/en2b/quizapi/game/GameServiceTest.java
Fixing for database and getting the question
> fix: removed category and language from question

- api/src/main/java/lab/en2b/quizapi/game/GameService.java
- api/src/main/resources/application.properties
- docs/src/08_concepts.adoc
Updated the doc.
Removed a couple of System.out.println();
Changed the DB from create to validate.
> Updated the doc and little changes

- webapp/public/locales/en/translation.json
- webapp/public/locales/es/translation.json
- webapp/src/components/statistics/UserStatistics.jsx
- webapp/src/pages/Rules.jsx
- webapp/src/pages/Statistics.jsx
- webapp/src/tests/LateralMenu.test.js
- webapp/src/tests/Statistics.test.js
New version of the UI for the Statistics and Rules pages.
> Statistics and Rules UI redesign

- api/src/main/java/lab/en2b/quizapi/questions/question/QuestionService.java
- api/src/main/java/lab/en2b/quizapi/questions/question/dtos/QuestionResponseDto.java
- api/src/main/java/lab/en2b/quizapi/questions/question/mappers/QuestionResponseDtoMapper.java
- api/src/test/java/lab/en2b/quizapi/questions/QuestionServiceTest.java
- questiongenerator/src/main/java/Main.java
- questiongenerator/src/main/java/model/Question.java
- questiongenerator/src/main/java/repositories/GeneralRepositoryStorer.java
- questiongenerator/src/main/java/templates/PaintingQuestion.java
- questiongenerator/src/main/java/templates/StadiumQuestion.java
Added image to questions, the url is concatenated with the String "#* &%", the constraints are erased from the DB, but not recreated as i suspect that they are created by the spring project.
There are changes needed to the backend to make it easy for the frontend to show them
> Feat: Added image questions

- docker-compose.yml
This PR should fix an error I had not realized it could happen: the reverse proxy not deploying on release (and thus crashing the entire application.
> fix: add proxy deployment on release

- api/src/main/java/lab/en2b/quizapi/game/GameRepository.java
I have found a missing SELECT in a query. This PR should fix it.
> Fix: missing 'SELECT' in API

- webapp/src/components/statistics/UserStatistics.jsx
Working in the new game implementation with the new menu, I have found in UserStatistics that causes infinite petitions to be sent if the user statistics do not exist. This bug also caused two statistics entries to be created in database, so it kept failing not because it did not have the user statistics, but because there where two entries retrieved.
> Fix: Infinite petitions if user statistics do not exist

- webapp/src/pages/Game.jsx
This PR should fix a bug regarding page refresh when a game is running.
> fix: re-refreshing not handling correctly page updates

- webapp/src/pages/Dashboard.jsx
- webapp/src/pages/Results.jsx
- webapp/src/tests/Dashboard.test.js
This pull requests adds the missing dashboard tests.
> Tests for dashboard page

- Quickstart.md
- README.md
This PR updates the readme and the quickstart guide.
> Updated the readme and the quickstart files

- api/src/main/java/lab/en2b/quizapi/questions/question/QuestionHelper.java
This code was written in case we were to add distractors in different ways, but we did not so it is better to remove it
> Fix: Eliminated unnecessary code

- webapp/src/components/GoBack.jsx
- webapp/src/pages/Results.jsx
- webapp/src/pages/Statistics.jsx
Adding the button to access the LateralMenu in the Results page and making all the GoBack buttons in the app to follow the same convention
> Adding menu button to the results page and goBack buttons follow conventions

- docs/src/12_glossary.adoc
- docs/src/13_annex.adoc
Some changes in section 12 and 13
> Some updates to the docu

- webapp/public/locales/en/translation.json
- webapp/public/locales/es/translation.json
- webapp/src/pages/Signup.jsx
Now we do not permit registering with empty confirmPassword layer.
> Sending error when confirmPassword is blank

- webapp/src/components/statistics/UserStatistics.jsx
- webapp/src/pages/Game.jsx
- webapp/src/pages/Signup.jsx
* Loading wheel in between questions was added
* User statistics component slightly modified
> UI improvements
