Arquisoft/wiq_en2b

README.md
Incorporating a 'Contributors' section into the README file and including my name.
=> chore: Add my name to the readme

docs/src/02_architecture_constraints.adoc
A hotfix for the documentation build.
=> hotfix: sidebar warning when building docs fixed

api/src/test/java/lab/en2b/quizapi/questions/QuestionControllerTest.java
Fixed a test in QuestionControllerTest that was crashing,
=> fix: broken question controller test

.github/workflows/build.yml, sonar-project.properties
This pull request itself will be used for testing whether it works.
=> Added Java Spring Boot project to SonarCloud 

.github/workflows/build.yml, api/lombok.config, api/pom.xml, api/src/main/java/lab/en2b/quizapi/auth/AuthController.java, api/src/main/java/lab/en2b/quizapi/auth/AuthService.java, api/src/main/java/lab/en2b/quizapi/auth/config/UserDetailsImpl.java, api/src/main/java/lab/en2b/quizapi/auth/dtos/RefreshTokenResponseDto.java, api/src/main/java/lab/en2b/quizapi/commons/user/UserService.java, api/src/main/java/lab/en2b/quizapi/questions/answer/Answer.java, api/src/main/java/lab/en2b/quizapi/questions/answer/dtos/AnswerDto.java, api/src/main/java/lab/en2b/quizapi/questions/answer/dtos/AnswerResponseDto.java, api/src/main/java/lab/en2b/quizapi/questions/answer/mappers/AnswerResponseDtoMapper.java, api/src/main/java/lab/en2b/quizapi/questions/question/Question.java, api/src/main/java/lab/en2b/quizapi/questions/question/QuestionController.java, api/src/main/java/lab/en2b/quizapi/questions/question/QuestionService.java, api/src/main/java/lab/en2b/quizapi/questions/question/dtos/AnswerCheckResponseDto.java, api/src/main/java/lab/en2b/quizapi/questions/question/dtos/QuestionResponseDto.java, api/src/test/java/lab/en2b/quizapi/QuizApiApplicationTests.java, api/src/test/java/lab/en2b/quizapi/auth/AuthControllerTest.java, api/src/test/java/lab/en2b/quizapi/auth/AuthServiceTest.java, api/src/test/java/lab/en2b/quizapi/questions/QuestionControllerTest.java, api/src/test/java/lab/en2b/quizapi/questions/QuestionServiceTest.java, sonar-project.properties
- Fixed /questions/{id}/answer endpoint _(woops)_
- Written tests for QuestionController
- Started writing tests for QuestionService
=> Fixed mistakes found within AnswerQuestion and started testing of QuestionController/QuestionService

webapp/src/tests/Login.test.js
Adding the login view tests which disappeared unexpectedly.
=> feat: adding the login tests.

webapp/src/pages/Signup.jsx
This hotfix should solve e2e build problems encountered in the deployment of release 0.1.0.
=> hotfix: removed unused Button import

webapp/src/tests/Login.test.js
Fixing again the login unit tests in the webapp.
=> fix: fixing the loginTests to work correctly.

api/src/main/java/lab/en2b/quizapi/auth/AuthController.java, api/src/main/java/lab/en2b/quizapi/commons/user/UserRepository.java, api/src/main/java/lab/en2b/quizapi/commons/user/UserService.java, api/src/test/java/lab/en2b/quizapi/auth/AuthServiceTest.java
- auto login added
- descriptive message for duplicated username
=> feat: auto login when registering user

api/monitoring/grafana/provisioning/dashboards/dashboard.yml, api/monitoring/grafana/provisioning/dashboards/example-service-dashboard.json, api/monitoring/grafana/provisioning/datasources/datasources.yml, api/monitoring/prometheus/prometheus.yml, api/pom.xml, api/src/main/resources/application.properties, docker-compose.yml
- prometheus docker has been readded
- graphana docker has been readded
- prometheus and grafana have been configured for spring boot
=> chore: added prometheus and grafana configuration

webapp/package-lock.json, webapp/package.json, webapp/src/components/ButtonEf.jsx, webapp/src/components/auth/AuthManager.js, webapp/src/components/game/Questions.js, webapp/src/components/utils/ProtectedRoute.jsx, webapp/src/index.js, webapp/src/pages/Game.jsx, webapp/src/pages/Login.jsx, webapp/src/pages/Signup.jsx
Several QoL improvements have been added:
- Auto-login after register in the webapp.
- Circular progress bar when checking whether the user is logged in.
- Support to login and register using 'enter' key.
- Slight change to how the unique axios instance handles headers.
- Invalidate Authorization header and JWT Refresh token on logout.
Closes #125.
=> QoL improvements

webapp/src/components/auth/AuthManager.js, webapp/src/pages/Login.jsx, webapp/src/pages/Root.jsx, webapp/src/pages/Signup.jsx
This PR fixes session not being kept between tabs, and also not redirecting to dashboard if the user enter /, /login or /signup.
=> Fix session not being kept between tabs

webapp/package-lock.json, webapp/package.json
This fixes a dependency problem found in the latest version of the develop branch.
=> fix: add missing dependency

api/src/main/java/lab/en2b/quizapi/questions/question/QuestionHelper.java, api/src/main/java/lab/en2b/quizapi/questions/question/QuestionService.java
Now the frontend recieves 4 answers, the correct one and 3 distractors, for now only 2 are shown.
Changed a Math.random call for a Collections.shuffle (technically safer).
=> Added more distractors and fix security hotspot

webapp/src/components/LateralMenu.jsx, webapp/src/pages/About.jsx, webapp/src/pages/Dashboard.jsx, webapp/src/pages/Game.jsx, webapp/src/pages/Login.jsx, webapp/src/pages/Root.jsx, webapp/src/pages/Rules.jsx, webapp/src/pages/Signup.jsx, webapp/src/pages/Statistics.jsx, webapp/src/tests/Dashboard.test.js, webapp/src/tests/LateralMenu.test.js, webapp/src/tests/Root.test.js, webapp/src/tests/Rules.test.js
I fixed some warnings and errors in the tests due to act.
=> Fixing the warnings in the tests.

webapp/src/pages/Root.jsx
Remove an unused variable from the frontend.
=> Remove an unused variable from frontend

api/src/main/resources/application.properties
=> fix: create 2 validate

docker-compose.yml, webapp/src/components/LateralMenu.jsx
This PR maps the frontend HTTP server to the port 80, and fixes a minor issue regarding the URL to the API docs.
=> Various minor QoL fixes to the frontend

api/src/main/java/lab/en2b/quizapi/game/Game.java
Fixing the conditions for the new round
=> fix: new round conditions

webapp/src/pages/Dashboard.jsx
Fixed and error that the webapp was not checking if a game was active.
=> fix: fixed an error checking if the game is active.

webapp/package-lock.json, webapp/package.json, webapp/src/pages/Game.jsx, webapp/src/tests/Game.test.js
This PR should add the tests of the game UI to the webapp that were missing.
=> Tests: add game UI tests

webapp/src/components/game/Game.js, webapp/src/pages/Game.jsx
This PR should fix changing the language but not the game's language.
=> fix: changing language now changes game language

.github/workflows/release.yml, api/src/main/java/lab/en2b/quizapi/commons/utils/GameModeUtils.java, api/src/main/java/lab/en2b/quizapi/game/GameService.java, api/src/main/java/lab/en2b/quizapi/questions/question/QuestionCategory.java, api/src/main/java/lab/en2b/quizapi/questions/question/QuestionRepository.java, api/src/main/java/lab/en2b/quizapi/questions/question/QuestionService.java, api/src/test/java/lab/en2b/quizapi/game/GameServiceTest.java, api/src/test/java/lab/en2b/quizapi/questions/QuestionServiceTest.java
- added removal of docker images after becoming stale
- added removal of game when no questions can be added
- removed music question category
=> fixed bugs with application

webapp/src/components/dashboard/CustomGameMenu.jsx, webapp/src/components/game/Game.js
Now if a custom game is created, the selected game modes are sent correctly. I have also removed repeated code.
=> Fixed a bug in the custom game in the dashboard

docs/src/04_solution_strategy.adoc
Added the QG package distribution in the section 4.
=> Added the QG package distribution

webapp/public/index.html
This PR should provide a better page description
=> fix: page description
